# Generated by Django 3.0.5 on 2021-05-02 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainImage', models.ImageField(upload_to='aboutPics')),
                ('imagedate', models.IntegerField()),
                ('informationsAboutYou', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Advices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advicesFor', models.CharField(max_length=100)),
                ('adviceContent', models.TextField()),
                ('adviceImage', models.ImageField(blank=True, upload_to='advicesimages')),
                ('url', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AtheteTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comprtitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionName', models.CharField(max_length=50)),
                ('competitions', models.ImageField(blank=True, upload_to='aboutPics/competitions')),
                ('imagedate', models.IntegerField()),
                ('competitionsText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('sexe_male', models.CharField(max_length=5)),
                ('sexe_female', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('phone_number', models.IntegerField()),
                ('subject', models.TextField()),
                ('pull', models.IntegerField()),
                ('push', models.IntegerField()),
                ('squat', models.IntegerField()),
                ('dlift', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Courtsey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('SocielMediaPost', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='courtsey_images')),
            ],
        ),
        migrations.CreateModel(
            name='DayUserWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='imagesofdayuserwrkt')),
                ('ClientUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExcercisesMusclesPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExercisesForPublic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseName', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='exercisespublic')),
                ('url', models.TextField(blank=True)),
                ('musclePart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnesswithramzi.ExcercisesMusclesPart')),
            ],
        ),
        migrations.CreateModel(
            name='ExercisesMuscles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='gallery_images')),
                ('place', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramsWorkoutForPub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programName', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='programswktpublic')),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='SlideImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='slide_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainImage', models.ImageField(upload_to='aboutPics')),
                ('imagedate', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPointProgramType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnesswithramzi.ProgramType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramsWorkoutForPubDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('exerciseName', models.CharField(max_length=80)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='programWkt_public_images')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnesswithramzi.ProgramsWorkoutForPub')),
            ],
        ),
        migrations.AddField(
            model_name='programsworkoutforpub',
            name='programType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnesswithramzi.ProgramType'),
        ),
        migrations.CreateModel(
            name='ProgramsNutForPub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programName', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='programswktpublic')),
                ('desc', models.TextField(blank=True)),
                ('programType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnesswithramzi.ProgramType')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPersonalWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseName', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='programWkt_client_images')),
                ('urlYoutubeVedio', models.TextField(blank=True)),
                ('clientProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnesswithramzi.DayUserWorkout')),
            ],
        ),
        migrations.CreateModel(
            name='Program_Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('listNutrition', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='programNut_client_images')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clients_images')),
                ('weight', models.IntegerField()),
                ('addAnyThing', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repaNumber', models.IntegerField()),
                ('url', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='programsNutPers')),
                ('userProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnesswithramzi.UserPointProgramType')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='PersonalAdvicesImages')),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExercisesForPublicDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='exercisespublicDet')),
                ('url', models.TextField(blank=True)),
                ('exBelongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnesswithramzi.ExercisesForPublic')),
            ],
        ),
        migrations.AddField(
            model_name='excercisesmusclespart',
            name='muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnesswithramzi.ExercisesMuscles'),
        ),
    ]
