from django.contrib import admin
from .models import *

# Register your models he
admin.site.register(SlideImages)
admin.site.register(Gallery)
admin.site.register(Contact)
admin.site.register(ProfilInfo)
admin.site.register(Program_Nutrition)
admin.site.register(DayUserWorkout)
admin.site.register(ExercisesMuscles)
admin.site.register(ExcercisesMusclesPart)
admin.site.register(ExercisesForPublic)
admin.site.register(ExercisesForPublicDet)
admin.site.register(ProgramsWorkoutForPub)
admin.site.register(ProgramsWorkoutForPubDet)
admin.site.register(ProgramType)
admin.site.register(ProgramsNutForPub)
admin.site.register(About)
admin.site.register(Comprtitions)
admin.site.register(AtheteTable)
admin.site.register(Courtsey)
admin.site.register(Story)
admin.site.register(Advices)
admin.site.register(PersonalAdvice)
admin.site.register(UserPointProgramType)
admin.site.register(PersonalNutrition)
admin.site.register(ProgramPersonalWorkout)